services:
  - type: web
    name: weather-backend
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Dserver.port=${PORT} -jar target/weather-backend-1.0.0.jar
